### ISSUE TITLE
Add prettier!

### ISSUE THREAD

**Issue by mikeyhogarth** [OperationXen/cyberpunkCTF#13]
You've got loads of alignment issues and style inconsistencies: the solution to which is;

https://prettier.io/

There are two parts to this;

* A VSCode plugin that will auto-prettify on save
* A hook that will auto-prettify on git-commit (this means that whoever works on your code base, it'll get prettified whether then have the plugin or not)

Approach would be;

1) Prettify the whole app
2) Put the hook in
3) (optional but awesome) get the plugin so it auto-formats on save

Feel free to close if you don't agree, or also feel free to assign to me and I'll do (1 & 2)

**Comment by OperationXen** [comment]
I've added the plug in, will apply autoformatting to existing files manually

**Comment by mikeyhogarth** [comment]
I did you the pre-commit hook if you want it in #18
